#!/bin/bash

# node index.js &>/dev/null

command=$(node convert_to_list.js)

options=$(echo -e "$command" | awk -F '->' '{print $1}')
links=$(echo -e "$command" | awk -F '->' '{print $2}')

selection="$(echo -e "$command" | dmenu -i -p 'Choose Manga')"

echo "$selection" | awk -F '->' '{print $2}' | xargs -I {} xdg-open {}
